-- Specify which database to use
USE c_cs108_hzheng1;

DROP TABLE IF EXISTS Gift;
DROP TABLE IF EXISTS Challenge;
DROP TABLE IF EXISTS ItemInstance;
DROP TABLE IF EXISTS Pet;
DROP TABLE IF EXISTS Solutions;
DROP TABLE IF EXISTS World;
DROP TABLE IF EXISTS GameLevel;
DROP TABLE IF EXISTS Account;
DROP TABLE IF EXISTS Item;